apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.applicationName }}-svc"
spec:
  ports:
  - name: "80"
    port: {{ .Values.port }}
    protocol: TCP
    targetPort: {{ .Values.port }}
  selector:
    app: {{ .Values.applicationName }}

